### ISSUE TITLE
Tokbox Stop screen share not working

### ISSUE THREAD

**Issue by anuj255** [aullman/opentok-camera-filters#13]
Tokboxjs Stop screen share is also not working when I using this API. When I try to stop screen share the chrome "stop sharing" popup will not close automatically.

**Comment by aullman** [comment]
Ah, this would be because we need to stop the original stream when you stop publishing. This is not getting cleaned up properly. I'll fix this.

**Comment by anuj255** [comment]
Is stop screen-share issue is fixed now?
